apiVersion: v1
kind: Service
metadata:
  name: energy-marketplace-frontend
  labels:
    app: energy-marketplace-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: energy-marketplace-frontend 